version: "3.8"
services:
    ftp-server:
        image: ibraransaridocker/ftp-server
        restart: always
        environment:
            FTP_PASS: ${FTP_PASS}
            FTP_USER: ${FTP_USER}
        ports:
            - "20-21:20-21"
            - "40000-40009:40000-40009"
        volumes:
            - ./src/assets/content:/home/${FTP_USER}
    website:
        image: portfolio:latest
        ports:
            - "80:80"
        volumes:
            - ./src/assets/content:/usr/share/nginx/html/assets/content
