version: "3.8"
services:
    ftp-server:
        image: ibraransaridocker/ftp-server
        restart: always
        environment:
            FTP_PASS: ${FTP_PASS}
            FTP_USER: ${FTP_USER}
            PASV_ADDRESS: ${PASV_ADDRESS}
            PASV_MIN_PORT: 9050
            PASV_MAX_PORT: 9060
        ports:
            - "9020-9021:20-21"
            - "9050-9060:9050-9060"
        volumes:
            - content:/home/${FTP_USER}
    website:
        image: mrangalo/portfolio-website-docker:master
        pull_policy: always
        ports:
            - "9000:80"
        volumes:
            - content:/usr/share/nginx/html/assets/content
volumes:
    content:
